# fly.toml app configuration file generated for crabcallr-ws-nameless-lake-4392 on 2026-01-28T15:39:25-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'crabcallr-ws'
primary_region = 'sjc'

[build]
  dockerfile = 'Dockerfile'

[env]
  NODE_ENV = 'production'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  min_machines_running = 1

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 10000
    soft_limit = 8000

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512

[metrics]
  port = 8080
  path = "/metrics"
